added splashScreen with fading text
mokuteki-io/dart-playgrounds pull request #11
Opened 2019-12-17 17:14 UTC by goranesine

added splashScreen, optinal we can adjust speed off fading and style the text

2019-12-17 18:55 UTC, goranesine commented
Just change timer duration on 200 or 150 milliseconds.I was doing some testings on 1000 milliseconds.

2019-12-17 19:08 UTC, matejthetree requested changes

2019-12-17 19:08 UTC, matejthetree commented on lib/main.dart
> +        initialRoute: "/splashScreen",
ovo mora ici preko `RouteName static const`

2019-12-17 19:08 UTC, matejthetree commented on lib/main.dart
> +        initialRoute: "/splashScreen",
splash screen nema /
route name za splash ide samo `splash screen`
home ima '/` jer ako stavis sljedecu rutu kao '/newRoute' onda ce automatski back ici na home.

tako moze ici i deep 
`/home/prva/druga` . ako odes na drugu rutu, automatski ce staviti prije nje prvu i home

2019-12-17 19:08 UTC, matejthetree commented on lib/router/router.dart
> +  static const splashScreen = "/splashScreen";
bez /

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +  Widget emptyWidget() {
prvo build funkcija pa onda widgeti

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +        fontSize: 40,
text style koristimo iz teme. 
Imas `Theme.of(context).textTheme.display1`
imas display od 1 do 4 sa razlicitim velicinama

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +  Widget newRouting() {
ovo nije widget funkcija jer ne vraca widget. za sada se cini kao `void` funkcija

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    mainWidget.toString() == emptyWidget().toString()
ovdje stavis
```
 switch (mainWidget.type) {
case _EmptyWidget: 
mainWidget = _TextOne();
...
```

Umjesto da imas funkciju gore za svaki widget, napravis novi private widget na dnu filea

```
class _EmptyWidget extends StatelessWidget {

@override 
Widget build () {
  return Container();
}
```
Tako za svaki widget

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    mainWidget = emptyWidget();
_mainWidget mora biti private. Bolje da ga nazoves currentWidget

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    mainWidget = emptyWidget();
refactor ide sa SHIFT F6
Ako nisi, ugasi FN tipke i nek ti F1 F2 budu za shortcute

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    Timer.periodic(Duration(milliseconds: 1000), (timer) {
timer moras spremiti u privatnu varijablu `_timer` tako da u dispose mozes pozvati `_timer.dispose()`

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +        if (positiveNegative == true) {
positiveNegative nije descriptive name. 
Bolje bi bilo da se zove `_increaseOpacity` i onda ako je true raste ako nije pada

2019-12-17 19:08 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +        backgroundColor: Colors.pink,
ovo nebi trebalo dirati. AppBar color se treba napraviti u MaterialApp. Ako i drugdje u kodu se postavlja background, napravi novi issue (add appbar background from Theme) i to ce ti biti slijedeci zadatak

2019-12-17 22:09 UTC, goranesine commented on lib/main.dart
> +        initialRoute: "/splashScreen",
Riješeno

2019-12-17 22:09 UTC, goranesine commented on lib/router/router.dart
> +  static const splashScreen = "/splashScreen";
Riješeno

2019-12-17 22:12 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +  Widget emptyWidget() {
Ovo ne razumijem?
Widgeti su mi deklarirani posebno i onda ih dinamički mijenjam unutar  Scaffolda koji ima build funkciju. Prosvjetli me.

2019-12-17 22:12 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +  Widget newRouting() {
Riješeno

2019-12-17 22:13 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    Timer.periodic(Duration(milliseconds: 1000), (timer) {
Timer sam zaustavio sa Timer.cancel()

2019-12-17 22:14 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +        if (positiveNegative == true) {
Riješeno

2019-12-18 14:38 UTC, matejthetree commented on lib/main.dart
> +        initialRoute: "/splashScreen",
cool. ako je rijeseno, onda pritisnes dole resolve conversation. kada rijesis sve, pushash nove promjene u isti branch i tagiras me nekako da dobijem mail.

2019-12-18 14:39 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +  Widget emptyWidget() {
Ovo je funkcija koja vraca widget. bolje je da je prvo build funkcija pa onda ispod nje sve ove funkcije, cisto radi preglednosti. 

A dole sam ti napisao komentar da umjesto funkcije napravis nove widgete kao nove klase

2019-12-18 14:40 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    Timer.periodic(Duration(milliseconds: 1000), (timer) {
gdje si to napravio? daj mi zalijepi liniju ili dio koda

2019-12-18 14:43 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    Timer.periodic(Duration(milliseconds: 1000), (timer) {
aha vidim dole. time zaustavis timer samo unutar callbacka.
ali u slucaju da cijeli Statefull widget bude disposan, timer ce ostati raditi i pasti ce ti test.
zato trebas spremiti timer u privatnu varijablu.

override dispose funkcije napravis i u njoj pocistis timer

2019-12-18 14:44 UTC, matejthetree commented
nakon sto rijesis sve stvari koje sam ti komentirao, gore u reviewers stisnej onaj bottun za rerequest review

2019-12-18 18:23 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    mainWidget.toString() == emptyWidget().toString()
Sve sam riješio,osim switcha.
Javlja mi da case expression must be constant.
Inače sa if else sve radi.

2019-12-18 19:45 UTC, matejthetree requested changes
Odlicno.

mana timera je to sto se opacity povecava za 0.1.

da si napravio animaciju koja ide od 0 do 1 i reverse, onda bi imao za svaki frame polako mijenjanje opacityja. bilo bi puno vise smooth. ovako ce biti manje smooth. ali je dovoljno dobro. 

cisto ti govorim za drugi put da ne zapinjes na timer 

kada napravis nove promjene, markaj resolve conversation na svaki.
Ponovo me pozovi na review.

pa cemo mergat

2019-12-18 19:45 UTC, matejthetree commented on lib/main.dart
> +        initialRoute: "/splashScreen",
Ovdje je jos uvijek string kao ruta

2019-12-18 19:45 UTC, matejthetree commented on lib/router/router.dart
> +  static const splashScreen = "/splashScreen";
Tu je jos uvijek splash sa crtom

2019-12-18 19:45 UTC, matejthetree commented on lib/main.dart
> +        initialRoute: "splashScreen",
RouteName.splashScreen

2019-12-18 19:45 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    _timer.cancel();
jel ima dispose na timeru ili samo cancel. ako je samo cancel, onda je dobro

2019-12-18 19:45 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +        backgroundColor: Colors.pink,
ne treba na appbar u splashu

2019-12-18 19:45 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +        backgroundColor: Colors.pink,
to sam zeznuo u prvom reviewu. Znaci splash je samo centrirani text u bodyu scaffolda

2019-12-18 19:45 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    // TODO: implement build
makni todo

2019-12-18 19:45 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    // TODO: implement build
makni todo

2019-12-18 19:45 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    // TODO: implement build
makni todo

2019-12-18 20:50 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    _timer.cancel();
samo cancel

2019-12-18 21:05 UTC, goranesine commented on lib/main.dart
> +        initialRoute: "splashScreen",
Riješeno

2019-12-18 21:07 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    // TODO: implement build
ok

2019-12-18 21:07 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    // TODO: implement build
ok

2019-12-18 21:07 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    // TODO: implement build
ok

2019-12-24 11:07 UTC, matejthetree approved these changes
fenomenalno!

2019-12-24 11:15 UTC, matejthetree commented
@goranesine sada mozes mergati

2019-12-24 11:15 UTC, matejthetree commented
@goranesine ides na merge pull request

2019-12-24 17:44 UTC, merged