fixed routes
mokuteki-io/dart-playgrounds pull request #12
Opened 2019-12-20 20:07 UTC by djkowa

In about page when flat button 'About' is pressed it closes the drawer.

2019-12-24 11:12 UTC, matejthetree requested changes

2019-12-24 11:12 UTC, matejthetree commented on lib/router/router.dart
> +          settings: RouteSettings(name: '/'),
sta bez ovog nema imena?
super find.

Jedna zamjena, umjesto da radite novi route settings, primite settings gore u switch

`settings: settings`

2019-12-24 11:12 UTC, matejthetree commented on lib/ui_pages/about_page.dart
> +              Navigator.pushReplacementNamed(context, RouteName.homePage),
ovdje neznate hoce li doci u about iz home pagea.

Defaultni leading je bio dobar. samo <- da napravi pop.
To treba ostati isto

2019-12-24 11:12 UTC, matejthetree commented on lib/widgets/drawer.dart
> +                route!= '/aboutPage'?
super.

Umjesto '/aboutPage' koristite `RouteName.aboutPage`

2019-12-24 11:12 UTC, matejthetree commented on lib/widgets/drawer.dart
> +              Navigator.pop(context);
cini mi se da nije formatirano dobro

2020-01-06 19:39 UTC, djkowa commented on lib/router/router.dart
> +          settings: RouteSettings(name: '/'),
resolved

2020-01-06 19:40 UTC, djkowa commented
we have applied changes to the routes as requested

2020-01-06 21:57 UTC, matejthetree approved these changes

2020-01-06 22:12 UTC, merged