#13-open-firebase-repository
mokuteki-io/dart-playgrounds pull request #18
Opened 2020-01-05 09:00 UTC by goranesine

2020-01-06 21:49 UTC, matejthetree requested changes

2020-01-06 21:49 UTC, matejthetree commented on lib/ui_pages/home.dart
> +      endDrawer: CustomDrawer(
fmt

2020-01-06 21:49 UTC, matejthetree commented on lib/ui_pages/home.dart
>          backgroundColor: Colors.pink,
remove

2020-01-06 21:49 UTC, matejthetree commented on lib/ui_pages/home.dart
> +      body: CoursesList(
fmt

2020-01-06 21:49 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +  Future<void> _signInAnonymously() async {
create FirebaseService

create this function inside firebase service
In providers map FirebaseService to value

2020-01-06 21:49 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +      print(e);
add `throw e`

2020-01-06 21:49 UTC, matejthetree commented on lib/ui_pages/splash_screen.dart
> +    _signInAnonymously();
here you will add Future() that will call 
`Provider.of<FirebaseService>(context).signInAnonymously()`

2020-01-06 21:49 UTC, matejthetree commented on test/golden_test.dart
>  import 'package:playground_app/ui_pages/splash_screen.dart';
call golden test the same name as the file, and place in same directory `test/ui_pages/splash_screen_test.dart`

2020-01-08 21:02 UTC, goranesine commented on lib/ui_pages/home.dart
> +      endDrawer: CustomDrawer(
Fixed

2020-01-08 21:18 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +  Future<void> _signInAnonymously() async {
I move the function in firebase service.

2020-01-08 21:19 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +      print(e);
moved from splshScreen

2020-01-08 21:37 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +    _signInAnonymously();
Fixed

2020-01-08 21:39 UTC, goranesine commented on test/golden_test.dart
>  import 'package:playground_app/ui_pages/splash_screen.dart';
Fixed

2020-01-08 21:41 UTC, goranesine commented on lib/ui_pages/splash_screen.dart
> +  Future<void> _signInAnonymously() async {
Map FirebaseService to value ?

2020-01-09 20:28 UTC, closed without merging