#27 added logout button in drawer
mokuteki-io/dart-playgrounds pull request #33
Opened 2020-01-26 16:15 UTC by lea88pu

Please review

2020-01-26 19:02 UTC, goranesine approved these changes

2020-01-26 20:07 UTC, matejthetree requested changes
Ostalo je super

2020-01-26 20:07 UTC, matejthetree commented on lib/mvos/ui/widgets/drawer.dart
> +                      print('ruta');
Print vani

2020-01-26 20:07 UTC, matejthetree commented on lib/mvos/ui/widgets/drawer.dart
> +                      print('ruta');
Makni

2020-01-26 20:07 UTC, matejthetree commented on lib/mvos/ui/widgets/drawer.dart
> +                  if (data2.loggedIn == true) {
Ovaj if treba ici na consumer.
```
Data2.loggedIn?Consumer(...):Contianer()
```
Ako nije logged in ide prazan kontner.

2020-01-27 20:25 UTC, matejthetree requested changes

2020-01-27 20:25 UTC, matejthetree commented on lib/mvos/ui/widgets/loginPage_form.dart
> +      padding: const EdgeInsets.only(left:8.0,right: 8.0),
you didnt format correctly

2020-01-28 20:33 UTC, djkowa reviewed
reviewed

2020-01-28 21:54 UTC, matejthetree approved these changes

2020-01-29 21:06 UTC, merged