#28 confirm email dialogue finished and extracted in new widget
mokuteki-io/dart-playgrounds pull request #36
Opened 2020-01-27 20:05 UTC by djkowa

confirm email dialogue finished

2020-01-27 20:23 UTC, matejthetree requested changes

2020-01-27 20:23 UTC, matejthetree commented on lib/mvos/ui/widgets/confirm_email_dialogue.dart
> +                Navigator.of(context).popAndPushNamed(RouteName.logInPage);
Better to make sure that all other routes are poped. This can happen that user can go back to create page.
So pop all other routes! :)

2020-01-28 20:31 UTC, lea88pu reviewed
reviewed

2020-01-30 22:12 UTC, matejthetree approved these changes

2020-01-30 22:20 UTC, merged