#14 implementation playground finished
mokuteki-io/dart-playgrounds pull request #39
Opened 2020-01-27 21:49 UTC by djkowa

2020-01-27 21:51 UTC, lea88pu reviewed
reviewed

2020-01-28 21:51 UTC, matejthetree requested changes
add pubspec yaml

2020-01-28 21:51 UTC, matejthetree commented on lib/mvos/ui/widgets/drawer.dart
> +          Divider(color: Colors.pink,thickness: 2,),
All this should be one PlagroundButton widget. And then you make
```
kAppEnvironment == AppEnvironment.develop
                    ? PlaygroundButton(): Container();
```

2020-01-28 21:51 UTC, matejthetree commented on lib/mvos/ui/widgets/my_custom_form.dart
> +class MyCustomForm extends StatefulWidget {
delete this

2020-01-28 21:51 UTC, matejthetree commented on lib/mvos/ui/widgets/playground.dart
> +class Playground extends StatefulWidget {
delete this

2020-01-30 22:20 UTC, matejthetree requested changes

2020-01-30 22:20 UTC, matejthetree commented on lib/mvos/ui/widgets/drawer.dart
> +          Divider(color: Colors.pink,thickness: 2,),
Znaci cijeli ovaj dio treba biti widget. I on treba ici ako je production/develop

2020-01-30 22:20 UTC, matejthetree commented on lib/mvos/ui/widgets/my_custom_form.dart
> +class MyCustomForm extends StatefulWidget {
Makni ovo ca

2020-01-30 22:20 UTC, matejthetree commented on lib/mvos/ui/widgets/playground.dart
> +
I ovo

2020-02-01 12:11 UTC, matejthetree requested changes
jos uvijek ne vidim promjene iz reviewa

2020-02-04 09:47 UTC, SempaiEcchi commented
@djkowa neka sljedeći commit message ima u sebi "Fixes #14"

2020-02-04 19:33 UTC, merged