Feature
mokuteki-io/dart-playgrounds pull request #5
Opened 2019-12-10 22:04 UTC by djkowa

about page defined

2019-12-13 12:53 UTC, matejthetree commented
Niste mi pročitali code comments. 

Na svaki pročitani treba ici :thumbsup: ili komentar

2019-12-13 13:56 UTC, djkowa commented on .gitignore
>  .packages
test comment

2019-12-13 13:58 UTC, matejthetree commented on lib/ui_pages/about_page.dart
> +      debugShowCheckedModeBanner: false,
Ne treba material app tu

2019-12-13 13:58 UTC, matejthetree commented on lib/ui_pages/about_page.dart
> +          automaticallyImplyLeading: false,
Ovdje ostaje leading back arrow. Actions je samo menu button koji treba biti widget za sebe. Pa ga samo stavimo. Uvijek poziva scaffold of

2019-12-13 13:58 UTC, matejthetree commented on lib/ui_pages/about_page.dart
> +                Text('About Page'),
Title je samo Text. Da si htio button prije titlea staviti ručno, isllo bi `leading: IconButton...`

2019-12-13 13:58 UTC, matejthetree commented on lib/ui_pages/home.dart
> +          title: Center(child: Text('Mokuteki.io Playgrounds')),
Ne treba center. Ima appbar centerTitle property

2019-12-13 13:58 UTC, matejthetree commented on lib/ui_pages/home.dart
> +          backgroundColor: Colors.pink,
Stavi u material app primary color kao pink pa ovo nece trebati.

2019-12-13 13:58 UTC, matejthetree commented on lib/ui_pages/home.dart
> +
Ata nebi tu u action trebao ici menuButton

2019-12-13 13:58 UTC, matejthetree commented on lib/widgets/drawer.dart
> +                  Navigator.push(context, MaterialPageRoute(
Treba pushat routu RouteName.about, umjesto da je tu radi.

2019-12-13 13:58 UTC, matejthetree commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
Open end drawer

2019-12-13 13:58 UTC, matejthetree commented on .gitignore
>  **/doc/api/
Test komentar

2019-12-13 13:58 UTC, matejthetree commented on .gitignore
> -**/android/**/gradle-wrapper.jar
zasto ne radi

2019-12-13 15:28 UTC, lea88pu commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
Probali smo staviti `.openEndDrawer(),` ali kada se pozove `MenuButton()` u actions, ne otvara nista. Tek kada u `Scaffold` dodamo `endDrawer:CustomDrawer(),` ali onda on zapravo niti ne koristi taj `MenuButton()`

2019-12-13 17:00 UTC, matejthetree commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
kako ne koristi, ne razumijem. 
u actions u scaffoldu ces dodati [MenuDrawer()]

2019-12-13 17:24 UTC, lea88pu commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
@matejthetree Pa kada maknem iz Scaffolda `endDrawer:`,  MenuButton() ne otvara ladicu.
Ovako radi:
`class _AboutPageState extends State<AboutPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      endDrawer: CustomDrawer(),
      appBar: AppBar(
        title: Text('About Page'),
      ),` 
A ovako ne radi:
`class _AboutPageState extends State<AboutPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(actions: <Widget>[
        MenuButton(),
      ],
        title: Text('About Page'),
      ),`

2019-12-13 17:25 UTC, matejthetree commented
tocno.

u svaki scaffold moras dodati end drawer

On Fri, Dec 13, 2019 at 6:24 PM lea88pu <notifications@github.com> wrote:

> *@lea88pu* commented on this pull request.
> ------------------------------
>
> In lib/widgets/menu_button.dart
> <https://github.com/mokuteki-io/dart-playgrounds/pull/5#discussion_r357750270>
> :
>
> > @@ -0,0 +1,18 @@
> +import 'package:flutter/material.dart';
> +
> +
> +class MenuButton extends StatelessWidget {
> +  const MenuButton({
> +    Key key,
> +  }) : super(key: key);
> +
> +  @override
> +  Widget build(BuildContext context) {
> +    return IconButton(
> +      icon: Icon(
> +        Icons.menu,
> +      ),
> +      onPressed: () => Scaffold.of(context).openDrawer(),
>
> @matejthetree <https://github.com/matejthetree> Pa kada maknem iz
> Scaffolda endDrawer:, MenuButton() ne otvara ladicu.
> Ovako radi:
> class _AboutPageState extends State<AboutPage> { @override Widget
> build(BuildContext context) { return Scaffold( endDrawer: CustomDrawer(),
> appBar: AppBar( title: Text('About Page'), ),
> A ovako ne radi:
> class _AboutPageState extends State<AboutPage> { @override Widget
> build(BuildContext context) { return Scaffold( appBar: AppBar(actions:
> <Widget>[ MenuButton(), ], title: Text('About Page'), ),
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mokuteki-io/dart-playgrounds/pull/5?email_source=notifications&email_token=ACMX5IWTP2F2M4UGFDXZBXLQYPAMPA5CNFSM4JZFP5ZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCPFAWIY#discussion_r357750270>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMX5IROYBOHLANAGS2OVYLQYPAMPANCNFSM4JZFP5ZA>
> .
>

2019-12-13 17:26 UTC, matejthetree commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
tocno. svaki scaffold treba imati end drawer. inace ga nema :D

2019-12-13 17:27 UTC, matejthetree commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
menu button ces dodati samo u scaffold koji ima end drawer.

2019-12-13 17:30 UTC, lea88pu commented on lib/widgets/menu_button.dart
> +      onPressed: () => Scaffold.of(context).openDrawer(),
Ali zasto da ga stavim kad radi i bez njega?

2019-12-13 17:56 UTC, matejthetree commented
hoces reci da se button pokaze i bez MenuButtona?

On Fri, Dec 13, 2019 at 6:30 PM lea88pu <notifications@github.com> wrote:

> *@lea88pu* commented on this pull request.
> ------------------------------
>
> In lib/widgets/menu_button.dart
> <https://github.com/mokuteki-io/dart-playgrounds/pull/5#discussion_r357752742>
> :
>
> > @@ -0,0 +1,18 @@
> +import 'package:flutter/material.dart';
> +
> +
> +class MenuButton extends StatelessWidget {
> +  const MenuButton({
> +    Key key,
> +  }) : super(key: key);
> +
> +  @override
> +  Widget build(BuildContext context) {
> +    return IconButton(
> +      icon: Icon(
> +        Icons.menu,
> +      ),
> +      onPressed: () => Scaffold.of(context).openDrawer(),
>
> Ali zasto da ga stavim kad radi i bez njega?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mokuteki-io/dart-playgrounds/pull/5?email_source=notifications&email_token=ACMX5IVZJDDUQU7MRWZDBA3QYPBDFA5CNFSM4JZFP5ZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCPFBOWY#discussion_r357752742>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMX5IXWXXPYPGGJNVMKRZDQYPBDFANCNFSM4JZFP5ZA>
> .
>

2019-12-13 18:21 UTC, lea88pu commented
Da radi i bez njega

pet, 13. pro 2019. u 18:56 matejthetree <notifications@github.com> napisao
je:

> hoces reci da se button pokaze i bez MenuButtona?
>
> On Fri, Dec 13, 2019 at 6:30 PM lea88pu <notifications@github.com> wrote:
>
> > *@lea88pu* commented on this pull request.
> > ------------------------------
> >
> > In lib/widgets/menu_button.dart
> > <
> https://github.com/mokuteki-io/dart-playgrounds/pull/5#discussion_r357752742
> >
> > :
> >
> > > @@ -0,0 +1,18 @@
> > +import 'package:flutter/material.dart';
> > +
> > +
> > +class MenuButton extends StatelessWidget {
> > + const MenuButton({
> > + Key key,
> > + }) : super(key: key);
> > +
> > + @override
> > + Widget build(BuildContext context) {
> > + return IconButton(
> > + icon: Icon(
> > + Icons.menu,
> > + ),
> > + onPressed: () => Scaffold.of(context).openDrawer(),
> >
> > Ali zasto da ga stavim kad radi i bez njega?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/mokuteki-io/dart-playgrounds/pull/5?email_source=notifications&email_token=ACMX5IVZJDDUQU7MRWZDBA3QYPBDFA5CNFSM4JZFP5ZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCPFBOWY#discussion_r357752742
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ACMX5IXWXXPYPGGJNVMKRZDQYPBDFANCNFSM4JZFP5ZA
> >
> > .
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/mokuteki-io/dart-playgrounds/pull/5?email_source=notifications&email_token=AMXIZSYYRUFJLW6Q7WVKFV3QYPEDPA5CNFSM4JZFP5ZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG2XXTA#issuecomment-565541836>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMXIZS6OXKOGL564OQP5GVDQYPEDPANCNFSM4JZFP5ZA>
> .
>

2019-12-13 20:04 UTC, djkowa commented
@matejthetree Napravili smo promjene i pushali

2019-12-15 22:43 UTC, matejthetree commented on lib/ui_pages/about_page.dart
> +class _AboutPageState extends State<AboutPage> {
zbog cega vam treba statefull widget? :D

2019-12-15 22:45 UTC, matejthetree requested changes
super. samo jos detalji. odlican posao

2019-12-15 22:45 UTC, matejthetree commented on lib/ui_pages/home.dart
> +class _HomePageState extends State<HomePage> {
ovdje isto ne vidim razlog za statefull

2019-12-15 22:45 UTC, matejthetree commented on lib/widgets/drawer.dart
> +              child: Text('About',style: TextStyle(fontSize: 20,fontStyle: FontStyle.italic) ),
mislim da ovdje fali formatting. dartfmt

2019-12-16 20:19 UTC, merged