Course CRUD
mokuteki-io/dart-playgrounds pull request #64
Opened 2020-02-09 22:00 UTC by SempaiEcchi

2020-02-09 22:01 UTC, SempaiEcchi commented
The pastebin fetch method may not be useful for this, but @djkowa and @lea88pu can copy it for lesson descriptions

2020-02-10 00:31 UTC, SempaiEcchi commented
@matejthetree možeš pogledati koji je razlog zašto se ActiveCourseO ne updatea u edit_course_form.dart, nego bi se updateak tek kad bi ošao back i ponovno u taj screen, ovaj if ispod widget build... zanemari

2020-02-10 10:50 UTC, matejthetree requested changes

2020-02-10 10:50 UTC, matejthetree commented on lib/mvos/model/course_model.dart
> +      activeCourse.name,
id bi trebao biti, umjesto name. Zato jer u firebase po id-u cemo uvijek naci tocan course

2020-02-10 10:50 UTC, matejthetree commented on lib/mvos/service/course_service.dart
> +  Future<String> getCourseID(String name) async {
ovo je ok jel radi :)
Ali si mogao staviti document id u Entity i u Observable, i onda direktno po document ID update taj course. Zato jer se moze desiti da dva coursa imaju isti name, i onda si ga fulao

2020-02-10 10:50 UTC, matejthetree commented on lib/mvos/service/course_service.dart
> +  void updateCourseData(String initialName,
ovdje ide id

2020-02-10 10:50 UTC, matejthetree commented on lib/mvos/ui/widgets/admin_list_tile.dart
> +                a.selectCourse(courseO: courseO);
odliccno

2020-02-10 10:53 UTC, SempaiEcchi commented on lib/mvos/model/course_model.dart
> +      activeCourse.name,
napravio sam da nađe ID kad mu daš ime, 
da onda dodam u courseO da ima final String firebaseID ?

2020-02-10 10:54 UTC, SempaiEcchi commented on lib/mvos/service/course_service.dart
> +  Future<String> getCourseID(String name) async {
budem dodao onda ID u E i O

2020-02-10 11:28 UTC, matejthetree commented
Cool. Document id.

On Mon, Feb 10, 2020, 11:54 AM Leo Radocaj <notifications@github.com> wrote:

> *@SempaiEcchi* commented on this pull request.
> ------------------------------
>
> In lib/mvos/service/course_service.dart
> <https://github.com/mokuteki-io/dart-playgrounds/pull/64#discussion_r376991854>
> :
>
> > @@ -32,6 +33,32 @@ class CourseService implements Disposable {
>          .then((snapshot) => snapshot.documents.first.reference.delete());
>    }
>
> +  Future<String> getCourseID(String name) async {
>
> budem dodao onda ID u E i O
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mokuteki-io/dart-playgrounds/pull/64?email_source=notifications&email_token=ACMX5IQL4HPOGCFV7VBZCTDRCEW7VA5CNFSM4KSEVCGKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCU24K2A#discussion_r376991854>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMX5IRUKY3VOH4UPZVZ57DRCEW7VANCNFSM4KSEVCGA>
> .
>

2020-02-10 12:01 UTC, matejthetree requested changes

2020-02-10 12:01 UTC, matejthetree commented on lib/mvos/model/course_model.dart
> +      {ActiveCourseO activeCourseO,
ovdje ne trebas slati cijeli O nego samo id

2020-02-10 13:28 UTC, matejthetree approved these changes

2020-02-10 13:43 UTC, merged